-- main data
require("prototypes.item")
require("prototypes.entity-item")
require("prototypes.entity-recipe")
require("prototypes.fluids")
require("prototypes.recipe-category")
require("prototypes.recipe")
require("prototypes.entity")
require("prototypes.tech")
require("prototypes.category")
require("data-final")
