
data:extend(
        {
            {
                type = "item-group",
                name = "fni",
                order = "f-b",
                inventory_order = "f-b",
                icon = "__factorio-not-included__/graphics/FNI.png",
                icon_size = 128,
            },
            {
                type = "item-group",
                name = "fni-buildings",
                order = "f-a",
                inventory_order = "f-a",
                icon = "__factorio-not-included__/graphics/FNIBuildings.png",
                icon_size = 128,
            },
            {
                type = "item-subgroup",
                name = "fni-building",
                group = "fni-buildings",
                order = "g-0",
            },
            {
                type = "item-subgroup",
                name = "fni-item",
                group = "fni",
                order = "g-f",
            },
            {
                type = "item-subgroup",
                name = "fni-fluid",
                group = "fni",
                order = "g-g",
            },
            {
                type = "item-subgroup",
                name = "fni-colony",
                group = "fni-buildings",
                order = "g-a",
            },
            {
                type = "item-subgroup",
                name = "fni-cooker",
                group = "fni-buildings",
                order = "g-b",
            },
            {
                type = "item-subgroup",
                name = "fni-farm",
                group = "fni-buildings",
                order = "g-c",
            },
            {
                type = "item-subgroup",
                name = "fni-pasture",
                group = "fni-buildings",
                order = "g-d",
            },
            {
                type = "item-subgroup",
                name = "fni-compost",
                group = "fni-buildings",
                order = "g-e",
            },
            {
                type = "item-subgroup",
                name = "fni-water-sieve",
                group = "fni-buildings",
                order = "g-f",
            },
            {
                type = "item-subgroup",
                name = "fni-air-cleaner",
                group = "fni-buildings",
                order = "g-g",
            },
            {
                type = "item-subgroup",
                name = "fni-carbon-skimmer",
                group = "fni-buildings",
                order = "g-h",
            },
            {
                type = "item-subgroup",
                name = "fni-gas-pump",
                group = "fni-buildings",
                order = "g-i",
            },
            {
                type = "item-subgroup",
                name = "fni-distiller",
                group = "fni-buildings",
                order = "g-j",
            },
            {
                type = "item-subgroup",
                name = "fni-terrarium",
                group = "fni-buildings",
                order = "g-k",
            },
            {
                type = "item-subgroup",
                name = "fni-textile-loom",
                group = "fni-buildings",
                order = "g-l",
            },
            {
                type = "item-subgroup",
                name = "fni-recycler",
                group = "fni-buildings",
                order = "g-m",
            },
            {
                type = "item-subgroup",
                name = "fni-electrolyzer",
                group = "fni-buildings",
                order = "g-m",
            },
            {
                type = "item-subgroup",
                name = "fni-fuel-generator",
                group = "fni-buildings",
                order = "g-n",
            },
            {
                type = "item-subgroup",
                name = "fni-h2-generator",
                group = "fni-buildings",
                order = "g-o",
            },
            {
                type = "item-subgroup",
                name = "fni-natural-gas-generator",
                group = "fni-buildings",
                order = "g-p",
            },
        }
)
