data:extend({
    {
        type = "recipe",
        name = "entity-colony-1",
        enabled = true,
        icon = "__factorio-not-included__/graphics/colony-1/entity/32.png",
        icon_size = 32,
        category = "crafting",
        subgroup = "fni-building",
        ingredients =
        {
            { "iron-plate", 10 },
            { "copper-plate", 10 },
            { "electronic-circuit", 6 },
            { "iron-stick", 8 },
            { "iron-gear-wheel", 12 },
        },
        result = "colony-1"
    },
    {
        type = "recipe",
        name = "entity-farm-1",
        result = "farm-1",
        enabled = true,
        icon = "__factorio-not-included__/graphics/farm-1/entity/32.png",
        icon_size = 32,
        category = "crafting",
        subgroup = "fni-building",
        ingredients =
        {
            { "copper-plate", 5 },
            { "electronic-circuit", 3 },
            { "iron-gear-wheel", 6 },
        },
    },
    {
        type = "recipe",
        name = "entity-pasture-1",
        result = "pasture-1",
        enabled = true,
        icon = "__factorio-not-included__/graphics/pasture-1/entity/32.png",
        icon_size = 32,
        category = "crafting",
        subgroup = "fni-building",
        ingredients =
        {
            { "copper-plate", 5 },
            { "electronic-circuit", 3 },
            { "iron-gear-wheel", 6 },
        },
    },
    {
        type = "recipe",
        name = "entity-cooker-1",
        result = "cooker-1",
        enabled = true,
        icon = "__factorio-not-included__/graphics/cooker-1/entity/32.png",
        icon_size = 32,
        category = "crafting",
        subgroup = "fni-building",
        ingredients =
        {
            { "iron-plate", 5 },
            { "copper-plate", 3 },
            { "electronic-circuit", 6 },
        },
    },
    {
        type = "recipe",
        name = "entity-water-sieve-1",
        result = "water-sieve-1",
        enabled = true,
        icon = "__factorio-not-included__/graphics/water-sieve-1/entity/32.png",
        icon_size = 32,
        category = "crafting",
        subgroup = "fni-building",
        ingredients =
        {
            { "iron-plate", 10 },
            { "copper-plate", 3 },
            { "electronic-circuit", 6 },
        },
    },
    {
        type = "recipe",
        name = "entity-compost-1",
        result = "compost-1",
        enabled = true,
        icon = "__factorio-not-included__/graphics/compost-1/entity/32.png",
        icon_size = 32,
        category = "crafting",
        subgroup = "fni-building",
        ingredients =
        {
            { "iron-plate", 10 },
            { "electronic-circuit", 6 },
        },
    },
    {
        type = "recipe",
        name = "entity-air-cleaner-1",
        result = "air-cleaner-1",
        enabled = true,
        icon = "__factorio-not-included__/graphics/air-cleaner-1/entity/32.png",
        icon_size = 32,
        category = "crafting",
        subgroup = "fni-building",
        ingredients =
        {
            { "iron-plate", 10 },
            { "iron-gear-wheel", 6 },
            { "electronic-circuit", 6 },
        },
    },
    {
        type = "recipe",
        name = "entity-carbon-skimmer-1",
        result = "carbon-skimmer-1",
        enabled = true,
        icon = "__factorio-not-included__/graphics/carbon-skimmer-1/entity/32.png",
        icon_size = 32,
        category = "crafting",
        subgroup = "fni-building",
        ingredients =
        {
            { "iron-plate", 10 },
            { "iron-gear-wheel", 6 },
            { "electronic-circuit", 6 },
        },
    },
    {
        type = "recipe",
        name = "entity-gas-pump-1",
        result = "gas-pump-1",
        enabled = true,
        icon = "__factorio-not-included__/graphics/gas-pump-1/entity/32.png",
        icon_size = 32,
        category = "crafting",
        subgroup = "fni-building",
        ingredients =
        {
            { "iron-plate", 10 },
            { "iron-gear-wheel", 8 },
            { "electronic-circuit", 6 },
        },
    },
    {
        type = "recipe",
        name = "entity-colony-2",
        enabled = false,
        icon = "__factorio-not-included__/graphics/colony-2/entity/32.png",
        icon_size = 32,
        category = "crafting",
        subgroup = "fni-building",
        ingredients =
        {
            { "steel-plate", 10 },
            { "copper-plate", 10 },
            { "electronic-circuit", 6 },
            { "iron-stick", 8 },
            { "iron-gear-wheel", 12 },
        },
        result = "colony-2"
    },

    {
        type = "recipe",
        name = "entity-farm-2-1",
        result = "farm-2-1",
        enabled = false,
        icon = "__factorio-not-included__/graphics/farm-2-1/entity/32.png",
        icon_size = 32,
        category = "crafting",
        subgroup = "fni-building",
        ingredients =
        {
            { "steel-plate", 5 },
            { "copper-plate", 5 },
            { "electronic-circuit", 3 },
            { "iron-gear-wheel", 6 },
        },
    },
    {
        type = "recipe",
        name = "entity-farm-2-2",
        result = "farm-2-2",
        enabled = false,
        icon = "__factorio-not-included__/graphics/farm-2-2/entity/32.png",
        icon_size = 32,
        category = "crafting",
        subgroup = "fni-building",
        ingredients =
        {
            { "steel-plate", 5 },
            { "copper-plate", 5 },
            { "electronic-circuit", 3 },
            { "iron-gear-wheel", 6 },
        },
    },
    {
        type = "recipe",
        name = "entity-pasture-2-1",
        result = "pasture-2-1",
        enabled = false,
        icon = "__factorio-not-included__/graphics/pasture-2-1/entity/32.png",
        icon_size = 32,
        category = "crafting",
        subgroup = "fni-building",
        ingredients =
        {
            { "steel-plate", 5 },
            { "copper-plate", 5 },
            { "electronic-circuit", 3 },
            { "iron-gear-wheel", 6 },
        },
    },
    {
        type = "recipe",
        name = "entity-pasture-2-2",
        result = "pasture-2-2",
        enabled = false,
        icon = "__factorio-not-included__/graphics/pasture-2-2/entity/32.png",
        icon_size = 32,
        category = "crafting",
        subgroup = "fni-building",
        ingredients =
        {
            { "steel-plate", 5 },
            { "copper-plate", 5 },
            { "electronic-circuit", 3 },
            { "iron-gear-wheel", 6 },
        },
    },
    {
        type = "recipe",
        name = "entity-distiller-1",
        result = "distiller-1",
        enabled = false,
        icon = "__factorio-not-included__/graphics/distiller-1/entity/32.png",
        icon_size = 32,
        category = "crafting",
        subgroup = "fni-building",
        ingredients =
        {
            { "steel-plate", 5 },
            { "copper-plate", 5 },
            { "electronic-circuit", 3 },
            { "iron-gear-wheel", 6 },
        },
    },
    {
        type = "recipe",
        name = "entity-terrarium-1",
        result = "terrarium-1",
        enabled = false,
        icon = "__factorio-not-included__/graphics/terrarium-1/entity/32.png",
        icon_size = 32,
        category = "crafting",
        subgroup = "fni-building",
        ingredients =
        {
            { "steel-plate", 5 },
            { "copper-plate", 5 },
            { "electronic-circuit", 3 },
            { "iron-gear-wheel", 6 },
        },
    },
    {
        type = "recipe",
        name = "entity-colony-3",
        result = "colony-3",
        enabled = false,
        icon = "__factorio-not-included__/graphics/colony-3/entity/32.png",
        icon_size = 32,
        category = "crafting",
        subgroup = "fni-building",
        ingredients =
        {
            { "steel-plate", 5 },
            { "copper-plate", 5 },
            { "advanced-circuit", 3 },
            { "iron-gear-wheel", 6 },
        },
    },
    {
        type = "recipe",
        name = "entity-farm-3-1",
        result = "farm-3-1",
        enabled = false,
        icon = "__factorio-not-included__/graphics/farm-3-1/entity/32.png",
        icon_size = 32,
        category = "crafting",
        subgroup = "fni-building",
        ingredients =
        {
            { "steel-plate", 5 },
            { "copper-plate", 5 },
            { "advanced-circuit", 3 },
            { "iron-gear-wheel", 6 },
        },
    },
    {
        type = "recipe",
        name = "entity-farm-3-2",
        result = "farm-3-2",
        enabled = false,
        icon = "__factorio-not-included__/graphics/farm-3-2/entity/32.png",
        icon_size = 32,
        category = "crafting",
        subgroup = "fni-building",
        ingredients =
        {
            { "steel-plate", 5 },
            { "copper-plate", 5 },
            { "advanced-circuit", 3 },
            { "iron-gear-wheel", 6 },
        },
    },
    {
        type = "recipe",
        name = "entity-pasture-3-1",
        result = "pasture-3-1",
        enabled = false,
        icon = "__factorio-not-included__/graphics/pasture-3-1/entity/32.png",
        icon_size = 32,
        category = "crafting",
        subgroup = "fni-building",
        ingredients =
        {
            { "steel-plate", 5 },
            { "copper-plate", 5 },
            { "advanced-circuit", 3 },
            { "iron-gear-wheel", 6 },
        },
    },
    {
        type = "recipe",
        name = "entity-pasture-3-2",
        result = "pasture-3-2",
        enabled = false,
        icon = "__factorio-not-included__/graphics/pasture-3-2/entity/32.png",
        icon_size = 32,
        category = "crafting",
        subgroup = "fni-building",
        ingredients =
        {
            { "steel-plate", 5 },
            { "copper-plate", 5 },
            { "advanced-circuit", 3 },
            { "iron-gear-wheel", 6 },
        },
    },
    {
        type = "recipe",
        name = "entity-textile-loom-1",
        result = "textile-loom-1",
        enabled = false,
        icon = "__factorio-not-included__/graphics/textile-loom-1/entity/32.png",
        icon_size = 32,
        category = "crafting",
        subgroup = "fni-building",
        ingredients =
        {
            { "steel-plate", 5 },
            { "copper-plate", 5 },
            { "advanced-circuit", 3 },
            { "iron-gear-wheel", 6 },
        },
    },
    {
        type = "recipe",
        name = "entity-recycler-1",
        result = "recycler-1",
        enabled = false,
        icon = "__factorio-not-included__/graphics/recycler-1/entity/32.png",
        icon_size = 32,
        category = "crafting",
        subgroup = "fni-building",
        ingredients =
        {
            { "steel-plate", 5 },
            { "copper-plate", 5 },
            { "advanced-circuit", 3 },
            { "iron-gear-wheel", 6 },
        },
    },
    {
        type = "recipe",
        name = "entity-electrolyzer-1",
        result = "electrolyzer-1",
        enabled = false,
        icon = "__factorio-not-included__/graphics/electrolyzer-1/entity/32.png",
        icon_size = 32,
        category = "crafting",
        subgroup = "fni-building",
        ingredients =
        {
            { "steel-plate", 5 },
            { "copper-plate", 5 },
            { "advanced-circuit", 3 },
            { "iron-gear-wheel", 6 },
        },
    },
    --    4
    {
        type = "recipe",
        name = "entity-colony-4",
        result = "colony-4",
        enabled = false,
        icon = "__factorio-not-included__/graphics/colony-4/entity/32.png",
        icon_size = 32,
        category = "crafting",
        subgroup = "fni-building",
        ingredients =
        {
            { "steel-plate", 5 },
            { "copper-plate", 5 },
            { "advanced-circuit", 6 },
            { "iron-gear-wheel", 6 },
        },
    },
    {
        type = "recipe",
        name = "entity-farm-4-1",
        result = "farm-4-1",
        enabled = false,
        icon = "__factorio-not-included__/graphics/farm-4-1/entity/32.png",
        icon_size = 32,
        category = "crafting",
        subgroup = "fni-building",
        ingredients =
        {
            { "steel-plate", 5 },
            { "copper-plate", 5 },
            { "advanced-circuit", 6 },
            { "iron-gear-wheel", 6 },
        },
    },
    {
        type = "recipe",
        name = "entity-farm-4-2",
        result = "farm-4-2",
        enabled = false,
        icon = "__factorio-not-included__/graphics/farm-4-2/entity/32.png",
        icon_size = 32,
        category = "crafting",
        subgroup = "fni-building",
        ingredients =
        {
            { "steel-plate", 5 },
            { "copper-plate", 5 },
            { "advanced-circuit", 6 },
            { "iron-gear-wheel", 6 },
        },
    },
    {
        type = "recipe",
        name = "entity-farm-4-3",
        result = "farm-4-3",
        enabled = false,
        icon = "__factorio-not-included__/graphics/farm-4-3/entity/32.png",
        icon_size = 32,
        category = "crafting",
        subgroup = "fni-building",
        ingredients =
        {
            { "steel-plate", 5 },
            { "copper-plate", 5 },
            { "advanced-circuit", 6 },
            { "iron-gear-wheel", 6 },
        },
    },
    {
        type = "recipe",
        name = "entity-pasture-4-1",
        result = "pasture-4-1",
        enabled = false,
        icon = "__factorio-not-included__/graphics/pasture-4-1/entity/32.png",
        icon_size = 32,
        category = "crafting",
        subgroup = "fni-building",
        ingredients =
        {
            { "steel-plate", 5 },
            { "copper-plate", 5 },
            { "advanced-circuit", 6 },
            { "iron-gear-wheel", 6 },
        },
    },
    {
        type = "recipe",
        name = "entity-pasture-4-2",
        result = "pasture-4-2",
        enabled = false,
        icon = "__factorio-not-included__/graphics/pasture-4-2/entity/32.png",
        icon_size = 32,
        category = "crafting",
        subgroup = "fni-building",
        ingredients =
        {
            { "steel-plate", 5 },
            { "copper-plate", 5 },
            { "advanced-circuit", 6 },
            { "iron-gear-wheel", 6 },
        },
    },
    {
        type = "recipe",
        name = "entity-pasture-4-3",
        result = "pasture-4-3",
        enabled = false,
        icon = "__factorio-not-included__/graphics/pasture-4-3/entity/32.png",
        icon_size = 32,
        category = "crafting",
        subgroup = "fni-building",
        ingredients =
        {
            { "steel-plate", 5 },
            { "copper-plate", 5 },
            { "advanced-circuit", 6 },
            { "iron-gear-wheel", 6 },
        },
    },
    {
        type = "recipe",
        name = "entity-fuel-generator",
        result = "fuel-generator",
        enabled = false,
        icon = "__factorio-not-included__/graphics/fuel-generator/entity/32.png",
        icon_size = 32,
        category = "crafting",
        subgroup = "fni-building",
        ingredients =
        {
            { "steel-plate", 5 },
            { "copper-plate", 5 },
            { "advanced-circuit", 6 },
            { "iron-gear-wheel", 6 },
        },
    },
    {
        type = "recipe",
        name = "entity-h2-generator",
        result = "h2-generator",
        enabled = false,
        icon = "__factorio-not-included__/graphics/h2-generator/entity/32.png",
        icon_size = 32,
        category = "crafting",
        subgroup = "fni-building",
        ingredients =
        {
            { "steel-plate", 5 },
            { "copper-plate", 5 },
            { "advanced-circuit", 6 },
            { "iron-gear-wheel", 6 },
        },
    },
-- 5
    {
        type = "recipe",
        name = "entity-colony-5",
        result = "colony-5",
        enabled = false,
        icon = "__factorio-not-included__/graphics/colony-5/entity/32.png",
        icon_size = 32,
        category = "crafting",
        subgroup = "fni-building",
        ingredients =
        {
            { "steel-plate", 5 },
            { "copper-plate", 5 },
            { "processing-unit", 6 },
            { "iron-gear-wheel", 6 },
        },
    },
    {
        type = "recipe",
        name = "entity-farm-5-1",
        result = "farm-5-1",
        enabled = false,
        icon = "__factorio-not-included__/graphics/farm-5-1/entity/32.png",
        icon_size = 32,
        category = "crafting",
        subgroup = "fni-building",
        ingredients =
        {
            { "steel-plate", 5 },
            { "copper-plate", 5 },
            { "processing-unit", 6 },
            { "iron-gear-wheel", 6 },
        },
    },
    {
        type = "recipe",
        name = "entity-farm-5-2",
        result = "farm-5-2",
        enabled = false,
        icon = "__factorio-not-included__/graphics/farm-5-2/entity/32.png",
        icon_size = 32,
        category = "crafting",
        subgroup = "fni-building",
        ingredients =
        {
            { "steel-plate", 5 },
            { "copper-plate", 5 },
            { "processing-unit", 6 },
            { "iron-gear-wheel", 6 },
        },
    },
    {
        type = "recipe",
        name = "entity-farm-5-3",
        result = "farm-5-3",
        enabled = false,
        icon = "__factorio-not-included__/graphics/farm-5-3/entity/32.png",
        icon_size = 32,
        category = "crafting",
        subgroup = "fni-building",
        ingredients =
        {
            { "steel-plate", 5 },
            { "copper-plate", 5 },
            { "processing-unit", 6 },
            { "iron-gear-wheel", 6 },
        },
    },
    {
        type = "recipe",
        name = "entity-pasture-5-1",
        result = "pasture-5-1",
        enabled = false,
        icon = "__factorio-not-included__/graphics/pasture-5-1/entity/32.png",
        icon_size = 32,
        category = "crafting",
        subgroup = "fni-building",
        ingredients =
        {
            { "steel-plate", 5 },
            { "copper-plate", 5 },
            { "processing-unit", 6 },
            { "iron-gear-wheel", 6 },
        },
    },
    {
        type = "recipe",
        name = "entity-pasture-5-2",
        result = "pasture-5-2",
        enabled = false,
        icon = "__factorio-not-included__/graphics/pasture-5-2/entity/32.png",
        icon_size = 32,
        category = "crafting",
        subgroup = "fni-building",
        ingredients =
        {
            { "steel-plate", 5 },
            { "copper-plate", 5 },
            { "processing-unit", 6 },
            { "iron-gear-wheel", 6 },
        },
    },
    {
        type = "recipe",
        name = "entity-pasture-5-3",
        result = "pasture-5-3",
        enabled = false,
        icon = "__factorio-not-included__/graphics/pasture-5-3/entity/32.png",
        icon_size = 32,
        category = "crafting",
        subgroup = "fni-building",
        ingredients =
        {
            { "steel-plate", 5 },
            { "copper-plate", 5 },
            { "processing-unit", 6 },
            { "iron-gear-wheel", 6 },
        },
    },
    {
        type = "recipe",
        name = "entity-natural-gas-generator",
        result = "natural-gas-generator",
        enabled = false,
        icon = "__factorio-not-included__/graphics/natural-gas-generator/entity/32.png",
        icon_size = 32,
        category = "crafting",
        subgroup = "fni-building",
        ingredients =
        {
            { "steel-plate", 5 },
            { "copper-plate", 5 },
            { "processing-unit", 6 },
            { "iron-gear-wheel", 6 },
        },
    },
})
