data:extend({
    {
        type = "item",
        name = "colony-1",
        icon = "__factorio-not-included__/graphics/colony-1/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        place_result = "colony-1",
        subgroup = "fni-item",
        stack_size = 20,
    },
    {
        type = "item",
        name = "farm-1",
        place_result = "farm-1",
        icon = "__factorio-not-included__/graphics/farm-1/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 20,
    },
    {
        type = "item",
        name = "pasture-1",
        place_result = "pasture-1",
        icon = "__factorio-not-included__/graphics/pasture-1/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 20,
    },
    {
        type = "item",
        name = "cooker-1",
        place_result = "cooker-1",
        icon = "__factorio-not-included__/graphics/cooker-1/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 20,
    },
    {
        type = "item",
        name = "water-sieve-1",
        place_result = "water-sieve-1",
        icon = "__factorio-not-included__/graphics/water-sieve-1/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 20,
    },
    {
        type = "item",
        name = "compost-1",
        place_result = "compost-1",
        icon = "__factorio-not-included__/graphics/compost-1/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 20,
    },
    {
        type = "item",
        name = "air-cleaner-1",
        place_result = "air-cleaner-1",
        icon = "__factorio-not-included__/graphics/air-cleaner-1/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 20,
    },
    {
        type = "item",
        name = "carbon-skimmer-1",
        place_result = "carbon-skimmer-1",
        icon = "__factorio-not-included__/graphics/carbon-skimmer-1/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 20,
    },
    {
        type = "item",
        name = "gas-pump-1",
        place_result = "gas-pump-1",
        icon = "__factorio-not-included__/graphics/gas-pump-1/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 20,
    },
})
