data:extend({
    {
        type = "fluid",
        name = "co2",
        icon = "__factorio-not-included__/graphics/co2/item/64.png",
        icon_size = 64,
        subgroup = "fni-fluid",
        base_color = { r = 0.8, g = 0, b = 0.7, a = 1 },
        flow_color = { r = 0.7, g = 0.7, b = 0.7, a = 1 },
        default_temperature = 15,
        max_temperature = 100,
        heat_capacity = "0.6KJ",
        pressure_to_speed_ratio = 0.15,
        flow_to_energy_ratio = 0.59,
        order = "c-a"
    },
    {
        type = "fluid",
        name = "polluted-water",
        icon = "__factorio-not-included__/graphics/polluted-water/item/64.png",
        icon_size = 64,
        subgroup = "fni-fluid",
        base_color = { r = 0.8, g = 0, b = 0.7, a = 1 },
        flow_color = { r = 0.7, g = 0.7, b = 0.7, a = 1 },
        default_temperature = 15,
        max_temperature = 100,
        heat_capacity = "0.6KJ",
        pressure_to_speed_ratio = 0.15,
        flow_to_energy_ratio = 0.59,
        order = "c-b"
    },
    {
        type = "fluid",
        name = "o2",
        icon = "__factorio-not-included__/graphics/o2/item/64.png",
        icon_size = 64,
        subgroup = "fni-fluid",
        base_color = { r = 0.8, g = 0, b = 0.7, a = 1 },
        flow_color = { r = 0.7, g = 0.7, b = 0.7, a = 1 },
        default_temperature = 15,
        max_temperature = 100,
        heat_capacity = "0.6KJ",
        pressure_to_speed_ratio = 0.15,
        flow_to_energy_ratio = 0.59,
        order = "c-b"
    },
    {
        type = "fluid",
        name = "n2",
        icon = "__factorio-not-included__/graphics/n2/item/64.png",
        icon_size = 64,
        subgroup = "fni-fluid",
        base_color = { r = 0.8, g = 0, b = 0.7, a = 1 },
        flow_color = { r = 0.7, g = 0.7, b = 0.7, a = 1 },
        default_temperature = 15,
        max_temperature = 100,
        heat_capacity = "0.6KJ",
        pressure_to_speed_ratio = 0.15,
        flow_to_energy_ratio = 0.59,
        order = "c-b"
    },
    {
        type = "fluid",
        name = "h2",
        icon = "__factorio-not-included__/graphics/h2/item/64.png",
        icon_size = 64,
        subgroup = "fni-fluid",
        base_color = { r = 0.8, g = 0, b = 0.7, a = 1 },
        flow_color = { r = 0.7, g = 0.7, b = 0.7, a = 1 },
        default_temperature = 15,
        max_temperature = 100,
        heat_capacity = "0.6KJ",
        pressure_to_speed_ratio = 0.15,
        flow_to_energy_ratio = 0.59,
        order = "c-b"
    },
    {
        type = "fluid",
        name = "polluted-oxygen",
        icon = "__factorio-not-included__/graphics/polluted-oxygen/item/64.png",
        icon_size = 64,
        subgroup = "fni-fluid",
        base_color = { r = 0.8, g = 0, b = 0.7, a = 1 },
        flow_color = { r = 0.7, g = 0.7, b = 0.7, a = 1 },
        default_temperature = 15,
        max_temperature = 100,
        heat_capacity = "0.6KJ",
        pressure_to_speed_ratio = 0.15,
        flow_to_energy_ratio = 0.59,
        order = "c-b"
    },
    {
        type = "fluid",
        name = "chlorine",
        icon = "__factorio-not-included__/graphics/chlorine/item/64.png",
        icon_size = 64,
        subgroup = "fni-fluid",
        base_color = { r = 0.8, g = 0, b = 0.7, a = 1 },
        flow_color = { r = 0.7, g = 0.7, b = 0.7, a = 1 },
        default_temperature = 15,
        max_temperature = 100,
        heat_capacity = "0.6KJ",
        pressure_to_speed_ratio = 0.15,
        flow_to_energy_ratio = 0.59,
        order = "c-a"
    },
    {
        type = "fluid",
        name = "drinkable-water",
        icon = "__factorio-not-included__/graphics/drinkable-water/item/64.png",
        icon_size = 64,
        subgroup = "fni-fluid",
        base_color = { r = 0.8, g = 0, b = 0.7, a = 1 },
        flow_color = { r = 0.7, g = 0.7, b = 0.7, a = 1 },
        default_temperature = 15,
        max_temperature = 100,
        heat_capacity = "0.6KJ",
        pressure_to_speed_ratio = 0.15,
        flow_to_energy_ratio = 0.59,
        order = "c-a"
    },
    {
        type = "fluid",
        name = "sparkling-water",
        icon = "__factorio-not-included__/graphics/sparkling-water/item/64.png",
        icon_size = 64,
        subgroup = "fni-fluid",
        base_color = { r = 0.8, g = 0, b = 0.7, a = 1 },
        flow_color = { r = 0.7, g = 0.7, b = 0.7, a = 1 },
        default_temperature = 15,
        max_temperature = 100,
        heat_capacity = "0.6KJ",
        pressure_to_speed_ratio = 0.15,
        flow_to_energy_ratio = 0.59,
        order = "c-a"
    },
    --    4
    {
        type = "fluid",
        name = "juice",
        icon = "__factorio-not-included__/graphics/juice/item/64.png",
        icon_size = 64,
        subgroup = "fni-fluid",
        base_color = { r = 0.8, g = 0, b = 0.7, a = 1 },
        flow_color = { r = 0.7, g = 0.7, b = 0.7, a = 1 },
        default_temperature = 15,
        max_temperature = 100,
        heat_capacity = "0.6KJ",
        pressure_to_speed_ratio = 0.15,
        flow_to_energy_ratio = 0.59,
        order = "c-a"
    },
    {
        type = "fluid",
        name = "natural-gas",
        icon = "__factorio-not-included__/graphics/natural-gas/item/64.png",
        icon_size = 64,
        subgroup = "fni-fluid",
        base_color = { r = 0.8, g = 0, b = 0.7, a = 1 },
        flow_color = { r = 0.7, g = 0.7, b = 0.7, a = 1 },
        default_temperature = 15,
        max_temperature = 100,
        heat_capacity = "0.6KJ",
        pressure_to_speed_ratio = 0.15,
        flow_to_energy_ratio = 0.59,
        order = "c-a"
    },
})
