data:extend({
    {
        type = "fluid",
        name = "co2",
        icon = "__factorio-not-included__/graphics/fluid/co2/32.png",
        icon_size = 32,
        subgroup = "fni-fluid",
        base_color = { r = 0.8, g = 0, b = 0.7, a = 1 },
        flow_color = { r = 0.7, g = 0.7, b = 0.7, a = 1 },
        default_temperature = 15,
        max_temperature = 100,
        heat_capacity = "0.6KJ",
        pressure_to_speed_ratio = 0.15,
        flow_to_energy_ratio = 0.59,
        order = "c-a"
    },
    {
        type = "fluid",
        name = "polluted-water",
        icon = "__factorio-not-included__/graphics/fluid/polluted-water/32.png",
        icon_size = 32,
        subgroup = "fni-fluid",
        base_color = { r = 0.8, g = 0, b = 0.7, a = 1 },
        flow_color = { r = 0.7, g = 0.7, b = 0.7, a = 1 },
        default_temperature = 15,
        max_temperature = 100,
        heat_capacity = "0.6KJ",
        pressure_to_speed_ratio = 0.15,
        flow_to_energy_ratio = 0.59,
        order = "c-b"
    },
    {
        type = "fluid",
        name = "o2",
        icon = "__factorio-not-included__/graphics/fluid/o2/32.png",
        icon_size = 32,
        subgroup = "fni-fluid",
        base_color = { r = 0.8, g = 0, b = 0.7, a = 1 },
        flow_color = { r = 0.7, g = 0.7, b = 0.7, a = 1 },
        default_temperature = 15,
        max_temperature = 100,
        heat_capacity = "0.6KJ",
        pressure_to_speed_ratio = 0.15,
        flow_to_energy_ratio = 0.59,
        order = "c-b"
    },
    {
        type = "fluid",
        name = "n2",
        icon = "__factorio-not-included__/graphics/fluid/n2/32.png",
        icon_size = 32,
        subgroup = "fni-fluid",
        base_color = { r = 0.8, g = 0, b = 0.7, a = 1 },
        flow_color = { r = 0.7, g = 0.7, b = 0.7, a = 1 },
        default_temperature = 15,
        max_temperature = 100,
        heat_capacity = "0.6KJ",
        pressure_to_speed_ratio = 0.15,
        flow_to_energy_ratio = 0.59,
        order = "c-b"
    },
    {
        type = "fluid",
        name = "h2",
        icon = "__factorio-not-included__/graphics/fluid/h2/32.png",
        icon_size = 32,
        subgroup = "fni-fluid",
        base_color = { r = 0.8, g = 0, b = 0.7, a = 1 },
        flow_color = { r = 0.7, g = 0.7, b = 0.7, a = 1 },
        default_temperature = 15,
        max_temperature = 100,
        heat_capacity = "0.6KJ",
        pressure_to_speed_ratio = 0.15,
        flow_to_energy_ratio = 0.59,
        order = "c-b"
    },
    {
        type = "fluid",
        name = "polluted-oxygen",
        icon = "__factorio-not-included__/graphics/fluid/polluted-oxygen/32.png",
        icon_size = 32,
        subgroup = "fni-fluid",
        base_color = { r = 0.8, g = 0, b = 0.7, a = 1 },
        flow_color = { r = 0.7, g = 0.7, b = 0.7, a = 1 },
        default_temperature = 15,
        max_temperature = 100,
        heat_capacity = "0.6KJ",
        pressure_to_speed_ratio = 0.15,
        flow_to_energy_ratio = 0.59,
        order = "c-b"
    },
})
