data:extend({
    {
        type = "item",
        name = "human-1",
        icon = "__factorio-not-included__/graphics/human-1/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "food-1",
        icon = "__factorio-not-included__/graphics/food-1/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "dirt",
        icon = "__factorio-not-included__/graphics/dirt/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "plant-1",
        icon = "__factorio-not-included__/graphics/plant-1/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "meat-1",
        icon = "__factorio-not-included__/graphics/meat-1/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "sand",
        icon = "__factorio-not-included__/graphics/sand/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "polluted-dirt",
        icon = "__factorio-not-included__/graphics/polluted-dirt/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "human-2",
        icon = "__factorio-not-included__/graphics/human-2/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "food-2",
        icon = "__factorio-not-included__/graphics/food-2/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "plant-2-1",
        icon = "__factorio-not-included__/graphics/plant-2-1/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "plant-2-2",
        icon = "__factorio-not-included__/graphics/plant-2-2/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "meat-2-1",
        icon = "__factorio-not-included__/graphics/meat-2-1/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "meat-2-2",
        icon = "__factorio-not-included__/graphics/meat-2-2/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "slime",
        icon = "__factorio-not-included__/graphics/slime/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "algae",
        icon = "__factorio-not-included__/graphics/algae/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "food-3",
        icon = "__factorio-not-included__/graphics/food-3/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "human-3",
        icon = "__factorio-not-included__/graphics/human-3/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "clothes-1",
        icon = "__factorio-not-included__/graphics/clothes-1/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "general-waste",
        icon = "__factorio-not-included__/graphics/general-waste/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "fiber",
        icon = "__factorio-not-included__/graphics/fiber/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
})
