data:extend({
    {
        type = "item",
        name = "human-1",
        icon = "__factorio-not-included__/graphics/item/human-1/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "food-1",
        icon = "__factorio-not-included__/graphics/item/food-1/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "dirt",
        icon = "__factorio-not-included__/graphics/item/dirt/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "plant-1",
        icon = "__factorio-not-included__/graphics/item/plant-1/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "meat-1",
        icon = "__factorio-not-included__/graphics/item/meat-1/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "sand",
        icon = "__factorio-not-included__/graphics/item/sand/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "polluted-dirt",
        icon = "__factorio-not-included__/graphics/item/polluted-dirt/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
})
