data:extend({
    {
        type = "item",
        name = "human-1",
        icon = "__factorio-not-included__/graphics/human-1/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "food-1",
        icon = "__factorio-not-included__/graphics/food-1/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "dirt",
        icon = "__factorio-not-included__/graphics/dirt/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "plant-1",
        icon = "__factorio-not-included__/graphics/plant-1/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "meat-1",
        icon = "__factorio-not-included__/graphics/meat-1/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "sand",
        icon = "__factorio-not-included__/graphics/sand/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 10,
    },
    {
        type = "item",
        name = "polluted-dirt",
        icon = "__factorio-not-included__/graphics/polluted-dirt/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "human-2",
        icon = "__factorio-not-included__/graphics/human-2/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "food-2",
        icon = "__factorio-not-included__/graphics/food-2/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "plant-2-1",
        icon = "__factorio-not-included__/graphics/plant-2-1/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "plant-2-2",
        icon = "__factorio-not-included__/graphics/plant-2-2/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "meat-2-1",
        icon = "__factorio-not-included__/graphics/meat-2-1/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "meat-2-2",
        icon = "__factorio-not-included__/graphics/meat-2-2/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "slime",
        icon = "__factorio-not-included__/graphics/slime/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "algae",
        icon = "__factorio-not-included__/graphics/algae/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "food-3",
        icon = "__factorio-not-included__/graphics/food-3/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "human-3",
        icon = "__factorio-not-included__/graphics/human-3/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "clothes-1",
        icon = "__factorio-not-included__/graphics/clothes-1/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "general-waste",
        icon = "__factorio-not-included__/graphics/general-waste/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "fiber",
        icon = "__factorio-not-included__/graphics/fiber/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "plant-3-1",
        icon = "__factorio-not-included__/graphics/plant-3-1/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "plant-3-2",
        icon = "__factorio-not-included__/graphics/plant-3-2/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "meat-3-1",
        icon = "__factorio-not-included__/graphics/meat-3-1/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "meat-3-2",
        icon = "__factorio-not-included__/graphics/meat-3-2/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    --    4
    {
        type = "item",
        name = "food-4",
        icon = "__factorio-not-included__/graphics/food-4/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "human-4",
        icon = "__factorio-not-included__/graphics/human-4/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "oversize-garbage",
        icon = "__factorio-not-included__/graphics/oversize-garbage/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "plant-4-1",
        icon = "__factorio-not-included__/graphics/plant-4-1/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "plant-4-2",
        icon = "__factorio-not-included__/graphics/plant-4-2/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "plant-4-3",
        icon = "__factorio-not-included__/graphics/plant-4-3/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "meat-4-1",
        icon = "__factorio-not-included__/graphics/meat-4-1/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "meat-4-2",
        icon = "__factorio-not-included__/graphics/meat-4-2/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "meat-4-3",
        icon = "__factorio-not-included__/graphics/meat-4-3/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "tv",
        icon = "__factorio-not-included__/graphics/tv/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    --    5
    {
        type = "item",
        name = "food-5",
        icon = "__factorio-not-included__/graphics/food-5/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "human-5",
        icon = "__factorio-not-included__/graphics/human-5/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "electric-garbage",
        icon = "__factorio-not-included__/graphics/electric-garbage/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "plant-5-1",
        icon = "__factorio-not-included__/graphics/plant-5-1/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "plant-5-2",
        icon = "__factorio-not-included__/graphics/plant-5-2/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "plant-5-3",
        icon = "__factorio-not-included__/graphics/plant-5-3/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "meat-5-1",
        icon = "__factorio-not-included__/graphics/meat-5-1/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "meat-5-2",
        icon = "__factorio-not-included__/graphics/meat-5-2/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "meat-5-3",
        icon = "__factorio-not-included__/graphics/meat-5-3/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "pc",
        icon = "__factorio-not-included__/graphics/pc/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "fashionable-clothes",
        icon = "__factorio-not-included__/graphics/fashionable-clothes/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    --    6
    {
        type = "item",
        name = "food-6",
        icon = "__factorio-not-included__/graphics/food-6/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "human-6",
        icon = "__factorio-not-included__/graphics/human-6/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "plant-6-1",
        icon = "__factorio-not-included__/graphics/plant-6-1/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "plant-6-2",
        icon = "__factorio-not-included__/graphics/plant-6-2/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "plant-6-3",
        icon = "__factorio-not-included__/graphics/plant-6-3/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "meat-6-1",
        icon = "__factorio-not-included__/graphics/meat-6-1/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "meat-6-2",
        icon = "__factorio-not-included__/graphics/meat-6-2/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "meat-6-3",
        icon = "__factorio-not-included__/graphics/meat-6-3/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "factory-game",
        icon = "__factorio-not-included__/graphics/factory-game/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "space-suite",
        icon = "__factorio-not-included__/graphics/space-suite/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "food-6",
        icon = "__factorio-not-included__/graphics/food-6/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "human-6",
        icon = "__factorio-not-included__/graphics/human-6/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "plant-6-1",
        icon = "__factorio-not-included__/graphics/plant-6-1/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "plant-6-2",
        icon = "__factorio-not-included__/graphics/plant-6-2/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "plant-6-3",
        icon = "__factorio-not-included__/graphics/plant-6-3/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "meat-6-1",
        icon = "__factorio-not-included__/graphics/meat-6-1/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "meat-6-2",
        icon = "__factorio-not-included__/graphics/meat-6-2/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "meat-6-3",
        icon = "__factorio-not-included__/graphics/meat-6-3/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "factory-game",
        icon = "__factorio-not-included__/graphics/factory-game/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
    {
        type = "item",
        name = "space-suite",
        icon = "__factorio-not-included__/graphics/space-suite/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 1,
    },
})
