    {
        type = "item",
        name = "$__1__$",
        place_result = "$__1__$",
        icon = "__factorio-not-included__/graphics/$__1__$/item/64.png",
        icon_size = 64,
        order = "w-b-a",
        subgroup = "fni-item",
        stack_size = 20,
    },
