name: release
on:
  push:
    tags:
      - '*'
jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup
        id: setup
        run: |-
          MOD_NAME=${FACTORIO_MOD_NAME}
          MOD_VERSION=${GITHUB_TAG/"refs/tags/"}
          echo "::set-output name=mod_name::${MOD_NAME}"
          echo "::set-output name=mod_version::${MOD_VERSION}"
        env:
          GITHUB_TAG: ${{ github.ref }}
          FACTORIO_MOD_NAME: factorio-not-included
      - name: Build
        id: build
        run: |-
          mkdir ${{ steps.setup.outputs.mod_name }}
          sed -e 's/"version": "1.0.0",/"version": "${{ steps.setup.outputs.mod_version }}",/g' ./info.json > ./info.json
          cp -r info.json graphics locale prototypes data.lua data-final.lua ${{ steps.setup.outputs.mod_name }}
          cat  ${{ steps.setup.outputs.mod_name }}/info.json
      - name: Package
        id: packaging
        uses: Roang-zero1/factorio-mod-package@master
        with:
          mod_base_dir: ${{ steps.setup.outputs.mod_name }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TAG: ${{ github.ref }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.packaging.outputs.asset_path }}
          asset_name: ${{ steps.setup.outputs.mod_name }}_${{ steps.setup.outputs.mod_version }}.zip
          asset_content_type: 'application/zip'